import { PrismaClient } from "@prisma/client";
import { hashPassword } from "@/lib/auth";

const prisma = new PrismaClient();

export async function GET(req: Request) {
  try {
    console.log("Clearing existing data…");

    await prisma.property.deleteMany();
    await prisma.users.deleteMany();

    await seedUsers();
    await seedProperties();

    console.log("Seed complete");
    return new Response("Seed successfully completed.");
  } catch (err) {
    console.error(err);
    return new Response("Internal Server Error", { status: 500 });
  }
}

async function seedUsers() {
  const users = [
    {
      uid: 1,
      name: "John Admin",
      email: "admin@gmail.com",
      password: "admin",
      dob: new Date("1995-01-01"),
      phone: "1234567890",
      ememail: "john2@gmail.com",
      isadmin: true,
    },
    {
      uid: 2,
      name: "Carl Guest",
      email: "guest@gmail.com",
      password: "guest",
      dob: new Date("1992-05-10"),
      phone: "9876543210",
      ememail: "carl2@gmail.com",
    },
    {
      uid: 3,
      name: "Jim Host",
      email: "host@gmail.com",
      password: "host",
      dob: new Date("1992-05-10"),
      phone: "9876543210",
      ememail: "jim2@gmail.com",
    },
  ];

  const usersWithHashedPasswords = await Promise.all(
    users.map(async (u) => ({
      ...u,
      password: await hashPassword(u.password),
    })),
  );

  await prisma.users.createMany({ data: usersWithHashedPasswords });
  console.log("Users seeded");
}

async function seedProperties() {
  console.log("Seeding properties…");

  const existingHost = await prisma.host.findUnique({ where: { uid: 3 } });
  if (!existingHost) {
    await prisma.host.create({
      data: {
        uid: 3,
        numhostratings: 0,
        avghostratings: 0,
        avgpropertyrating: 0,
      },
    });
    console.log("Created host: Jim Host");
  }

  const properties = [
    {
      name: "Uptown Modern Apt",
      maxguests: 3,
      numbedrooms: 1,
      description: "Bright apartment near restaurants and nightlife.",
      numbathrooms: 1,
      cancelperiod: "24_hours",
      refundrate: 0.5,
      nightlyfee: 110.0,
      cleaningfee: 35.0,
      servicefee: 12.0,
      street: "456 Oak Avenue",
      city: "Dallas",
      state: "Texas",
      zipcode: "75219",
      country: "USA",
      latitude: 32.8121,
      longitude: -96.802,
      hostuid: 3,
    },
    {
      name: "Suburban Family Home",
      maxguests: 6,
      numbedrooms: 3,
      description: "Spacious home in quiet neighborhood.",
      numbathrooms: 2,
      cancelperiod: "72_hours",
      refundrate: 0.8,
      nightlyfee: 180.0,
      cleaningfee: 60.0,
      servicefee: 20.0,
      street: "789 Maple Drive",
      city: "Plano",
      state: "Texas",
      zipcode: "75024",
      country: "USA",
      latitude: 33.0198,
      longitude: -96.6989,
      hostuid: 3,
    },
    {
      name: "Lakeview Studio",
      maxguests: 2,
      numbedrooms: 1,
      description: "Cozy studio with lake views and natural light.",
      numbathrooms: 1,
      cancelperiod: "Flexible",
      refundrate: 0.9,
      nightlyfee: 95.0,
      cleaningfee: 30.0,
      servicefee: 10.0,
      street: "321 Lakeshore Blvd",
      city: "Irving",
      state: "Texas",
      zipcode: "75039",
      country: "USA",
      latitude: 32.8601,
      longitude: -96.9447,
      hostuid: 3,
    },
    {
      name: "Downtown Loft",
      maxguests: 4,
      numbedrooms: 2,
      description: "Stylish loft in the heart of the city.",
      numbathrooms: 2,
      cancelperiod: "24_hours",
      refundrate: 0.7,
      nightlyfee: 150.0,
      cleaningfee: 40.0,
      servicefee: 15.0,
      street: "123 Main Street",
      city: "Dallas",
      state: "Texas",
      zipcode: "75201",
      country: "USA",
      latitude: 32.7767,
      longitude: -96.797,
      hostuid: 3,
    },
    {
      name: "Cozy Cottage",
      maxguests: 5,
      numbedrooms: 2,
      description: "Charming cottage near the lake.",
      numbathrooms: 1,
      cancelperiod: "Flexible",
      refundrate: 0.85,
      nightlyfee: 120.0,
      cleaningfee: 25.0,
      servicefee: 12.0,
      street: "987 Pine Lane",
      city: "Frisco",
      state: "Texas",
      zipcode: "75035",
      country: "USA",
      latitude: 33.1507,
      longitude: -96.8236,
      hostuid: 3,
    },
    {
      name: "Modern Condo",
      maxguests: 2,
      numbedrooms: 1,
      description: "Sleek condo with pool access.",
      numbathrooms: 1,
      cancelperiod: "24_hours",
      refundrate: 0.6,
      nightlyfee: 130.0,
      cleaningfee: 20.0,
      servicefee: 10.0,
      street: "555 Elm Street",
      city: "Arlington",
      state: "Texas",
      zipcode: "76011",
      country: "USA",
      latitude: 32.7357,
      longitude: -97.1081,
      hostuid: 3,
    },
    {
      name: "Beachfront Bungalow",
      maxguests: 6,
      numbedrooms: 3,
      description: "Steps from the water with stunning sunset views.",
      numbathrooms: 2,
      cancelperiod: "72_hours",
      refundrate: 0.8,
      nightlyfee: 220.0,
      cleaningfee: 50.0,
      servicefee: 18.0,
      street: "222 Seaside Drive",
      city: "Galveston",
      state: "Texas",
      zipcode: "77550",
      country: "USA",
      latitude: 29.3013,
      longitude: -94.7977,
      hostuid: 3,
    },
    {
      name: "Mountain Cabin",
      maxguests: 5,
      numbedrooms: 2,
      description: "Quiet cabin in the hills for a weekend getaway.",
      numbathrooms: 2,
      cancelperiod: "Flexible",
      refundrate: 0.9,
      nightlyfee: 160.0,
      cleaningfee: 35.0,
      servicefee: 15.0,
      street: "789 Pinecrest Road",
      city: "Granbury",
      state: "Texas",
      zipcode: "76048",
      country: "USA",
      latitude: 32.4382,
      longitude: -97.7949,
      hostuid: 3,
    },
    {
      name: "Urban Studio",
      maxguests: 2,
      numbedrooms: 1,
      description: "Compact studio perfect for short stays downtown.",
      numbathrooms: 1,
      cancelperiod: "24_hours",
      refundrate: 0.5,
      nightlyfee: 100.0,
      cleaningfee: 15.0,
      servicefee: 10.0,
      street: "101 City Street",
      city: "Dallas",
      state: "Texas",
      zipcode: "75202",
      country: "USA",
      latitude: 32.7801,
      longitude: -96.8003,
      hostuid: 3,
    },
    {
      name: "Luxury Villa",
      maxguests: 8,
      numbedrooms: 4,
      description: "High-end villa with pool and private chef.",
      numbathrooms: 3,
      cancelperiod: "Flexible",
      refundrate: 0.95,
      nightlyfee: 450.0,
      cleaningfee: 100.0,
      servicefee: 50.0,
      street: "900 Luxury Lane",
      city: "Dallas",
      state: "Texas",
      zipcode: "75219",
      country: "USA",
      latitude: 32.8105,
      longitude: -96.8007,
      hostuid: 3,
    },
    {
      name: "Historic Home",
      maxguests: 6,
      numbedrooms: 3,
      description: "Restored historic property in the city center.",
      numbathrooms: 2,
      cancelperiod: "72_hours",
      refundrate: 0.8,
      nightlyfee: 200.0,
      cleaningfee: 45.0,
      servicefee: 20.0,
      street: "77 Heritage Avenue",
      city: "Fort Worth",
      state: "Texas",
      zipcode: "76102",
      country: "USA",
      latitude: 32.7555,
      longitude: -97.3308,
      hostuid: 3,
    },
    {
      name: "Downtown Penthouse",
      maxguests: 4,
      numbedrooms: 2,
      description: "Penthouse with skyline views and luxury finishes.",
      numbathrooms: 2,
      cancelperiod: "24_hours",
      refundrate: 0.7,
      nightlyfee: 320.0,
      cleaningfee: 60.0,
      servicefee: 25.0,
      street: "400 Sky Street",
      city: "Dallas",
      state: "Texas",
      zipcode: "75201",
      country: "USA",
      latitude: 32.7805,
      longitude: -96.8,
      hostuid: 3,
    },
    {
      name: "Riverside Cottage",
      maxguests: 4,
      numbedrooms: 2,
      description: "Peaceful riverside cottage with private dock.",
      numbathrooms: 1,
      cancelperiod: "Flexible",
      refundrate: 0.85,
      nightlyfee: 140.0,
      cleaningfee: 30.0,
      servicefee: 15.0,
      street: "333 River Road",
      city: "Fort Worth",
      state: "Texas",
      zipcode: "76104",
      country: "USA",
      latitude: 32.7455,
      longitude: -97.32,
      hostuid: 3,
    },
    {
      name: "Modern Townhouse",
      maxguests: 4,
      numbedrooms: 2,
      description: "Townhouse with modern amenities and garage.",
      numbathrooms: 2,
      cancelperiod: "24_hours",
      refundrate: 0.6,
      nightlyfee: 155.0,
      cleaningfee: 35.0,
      servicefee: 12.0,
      street: "222 Oak Street",
      city: "Arlington",
      state: "Texas",
      zipcode: "76011",
      country: "USA",
      latitude: 32.736,
      longitude: -97.1085,
      hostuid: 3,
    },
    {
      name: "Quiet Bungalow",
      maxguests: 3,
      numbedrooms: 1,
      description: "Secluded bungalow perfect for relaxation.",
      numbathrooms: 1,
      cancelperiod: "Flexible",
      refundrate: 0.9,
      nightlyfee: 115.0,
      cleaningfee: 25.0,
      servicefee: 10.0,
      street: "101 Cedar Lane",
      city: "Irving",
      state: "Texas",
      zipcode: "75039",
      country: "USA",
      latitude: 32.86,
      longitude: -96.945,
      hostuid: 3,
    },
    {
      name: "City Apartment",
      maxguests: 2,
      numbedrooms: 1,
      description: "Compact apartment near shopping and transit.",
      numbathrooms: 1,
      cancelperiod: "24_hours",
      refundrate: 0.5,
      nightlyfee: 100.0,
      cleaningfee: 20.0,
      servicefee: 10.0,
      street: "555 Elm Street",
      city: "Dallas",
      state: "Texas",
      zipcode: "75202",
      country: "USA",
      latitude: 32.781,
      longitude: -96.799,
      hostuid: 3,
    },
    {
      name: "Luxury Condo",
      maxguests: 3,
      numbedrooms: 2,
      description: "Condo with rooftop pool and gym access.",
      numbathrooms: 2,
      cancelperiod: "72_hours",
      refundrate: 0.8,
      nightlyfee: 250.0,
      cleaningfee: 50.0,
      servicefee: 20.0,
      street: "888 Skyline Drive",
      city: "Dallas",
      state: "Texas",
      zipcode: "75201",
      country: "USA",
      latitude: 32.7815,
      longitude: -96.7985,
      hostuid: 3,
    },
    {
      name: "Seaside Villa",
      maxguests: 7,
      numbedrooms: 4,
      description: "Villa with private beach access and BBQ area.",
      numbathrooms: 3,
      cancelperiod: "Flexible",
      refundrate: 0.95,
      nightlyfee: 400.0,
      cleaningfee: 80.0,
      servicefee: 35.0,
      street: "777 Ocean Drive",
      city: "Galveston",
      state: "Texas",
      zipcode: "77550",
      country: "USA",
      latitude: 29.301,
      longitude: -94.798,
      hostuid: 3,
    },
    {
      name: "Charming Farmhouse",
      maxguests: 6,
      numbedrooms: 3,
      description: "Farmhouse with countryside views and large yard.",
      numbathrooms: 2,
      cancelperiod: "72_hours",
      refundrate: 0.85,
      nightlyfee: 190.0,
      cleaningfee: 40.0,
      servicefee: 18.0,
      street: "111 Country Road",
      city: "McKinney",
      state: "Texas",
      zipcode: "75069",
      country: "USA",
      latitude: 33.197,
      longitude: -96.6397,
      hostuid: 3,
    },
    {
      name: "Downtown Studio",
      maxguests: 2,
      numbedrooms: 1,
      description: "Modern studio close to downtown attractions.",
      numbathrooms: 1,
      cancelperiod: "24_hours",
      refundrate: 0.6,
      nightlyfee: 120.0,
      cleaningfee: 25.0,
      servicefee: 12.0,
      street: "202 Central Avenue",
      city: "Fort Worth",
      state: "Texas",
      zipcode: "76102",
      country: "USA",
      latitude: 32.755,
      longitude: -97.33,
      hostuid: 3,
    },
    {
      name: "Hilltop Retreat",
      maxguests: 5,
      numbedrooms: 3,
      description: "Spacious retreat with hilltop views and fireplace.",
      numbathrooms: 2,
      cancelperiod: "Flexible",
      refundrate: 0.9,
      nightlyfee: 175.0,
      cleaningfee: 35.0,
      servicefee: 15.0,
      street: "999 Summit Lane",
      city: "Granbury",
      state: "Texas",
      zipcode: "76048",
      country: "USA",
      latitude: 32.44,
      longitude: -97.795,
      hostuid: 3,
    },
    {
      name: "Garden Cottage",
      maxguests: 3,
      numbedrooms: 2,
      description: "Cottage with private garden and patio.",
      numbathrooms: 1,
      cancelperiod: "Flexible",
      refundrate: 0.85,
      nightlyfee: 130.0,
      cleaningfee: 25.0,
      servicefee: 12.0,
      street: "333 Blossom Street",
      city: "Frisco",
      state: "Texas",
      zipcode: "75035",
      country: "USA",
      latitude: 33.151,
      longitude: -96.824,
      hostuid: 3,
    },
    {
      name: "Penthouse Suite",
      maxguests: 4,
      numbedrooms: 2,
      description: "Luxury penthouse with skyline views and terrace.",
      numbathrooms: 2,
      cancelperiod: "24_hours",
      refundrate: 0.7,
      nightlyfee: 350.0,
      cleaningfee: 60.0,
      servicefee: 25.0,
      street: "404 Skyline Blvd",
      city: "Dallas",
      state: "Texas",
      zipcode: "75201",
      country: "USA",
      latitude: 32.78,
      longitude: -96.7995,
      hostuid: 3,
    },
  ];

  await prisma.property.createMany({ data: properties });
  console.log("Properties seeded");
}
